### ISSUE TITLE
运行QuoteApiTest的subscribeOrderBook测试方法，没有输出订单簿

### ISSUE THREAD

**Issue by JamesXiao** [ztsec/xtp_api_java#4]
步骤：运行QuoteApiTest的subscribeOrderBook测试方法
预期：onOrderBook回调打印出订单簿数据
实际效果：onSubOrderBook方法有回调，从返回数据看订阅是成功的，但onOrderBook没有被回调过。换了几只股票都是这样。

PS: 
1. 已经更新过代码库，subscribeTickByTick和subscribeMarketData的测试都正常，能打印出行情数据
2. 测试环境：61.152.102.110:8602

**Comment by 18033730900** [comment]
测试demo 测下下单 返回的 xtpId为 0，调用查看错误信息接口 什么都没有返回 什么问题呢

**Comment by ztsec** [comment]
orderbook只有深市的可以，测试环境是一段时间连深市行情、一段时间连沪市行情，是否是正好赶上推的是沪市行情。接口测试是正常的。
