### ISSUE TITLE
mac os throw UnsatisfiedLinkError

### ISSUE THREAD

**Issue by scemsjyd** [ztsec/xtp_api_java#5]
macos version：10.15
Exception info:

java.lang.UnsatisfiedLinkError: /usr/local/lib/libtradeplugin.dylib: dlopen(/usr/local/lib/libtradeplugin.dylib, 1): Library not loaded: /usr/local/lib/libglog.0.dylib
  Referenced from: /usr/local/lib/libtradeplugin.dylib
  Reason: image not found

**Comment by ztsec** [comment]
如果mac下遇到该问题，可以通过cp /usr/local/lib/libglog.dylib /usr/local/lib/libglog.0.dylib解决
